export const EID_TEMPLATES = [
  {
    id: 'template-photo-1',
    name: 'Classic Sheep',
    mood: 'Warm straw photo',
    image: '/assets/templates/template-photo-1.jpg',
    aspectRatio: '4 / 5',
    previewWidth: 'min(86vw, 400px)',
    objectPosition: 'center',
    messagePosition: 'bottom-8 right-7',
    messageWidth: 'max-w-[210px]',
    messageAlign: 'text-right items-end',
    messageTone: 'gold',
    messageWashClass: 'inset-x-0 bottom-0 h-[32%]',
    messageWashStyle: {
      background: 'linear-gradient(0deg, rgba(0,0,0,.5), rgba(0,0,0,.2), rgba(0,0,0,0))',
    },
    downloadText: { x: 0.84, y: 0.73, maxWidth: 0.42, align: 'right', wash: 'bottomBlack' },
  },
  {
    id: 'template-photo-2',
    name: 'Dark Ram',
    mood: 'Minimal premium',
    image: '/assets/templates/template-photo-2.jpg',
    aspectRatio: '4 / 5',
    previewWidth: 'min(86vw, 400px)',
    objectPosition: 'center',
    messagePosition: 'bottom-[12%] left-8',
    messageWidth: 'max-w-[210px]',
    messageAlign: 'text-left items-start',
    messageTone: 'ivory',
    messageWashClass: 'inset-x-0 bottom-0 h-[42%]',
    messageWashStyle: {
      background: 'linear-gradient(0deg, rgba(0,0,0,.6), rgba(0,0,0,.2), rgba(0,0,0,0))',
    },
    downloadText: { x: 0.16, y: 0.68, maxWidth: 0.42, align: 'left', wash: 'bottomBlackStrong' },
  },
  {
    id: 'template-photo-3',
    name: 'Kasturii Green',
    mood: 'Tall story card',
    image: '/assets/templates/template-photo-3.jpg',
    aspectRatio: '9 / 16',
    previewWidth: 'min(78vw, 335px)',
    objectPosition: 'center',
    messagePosition: 'bottom-8 right-6',
    messageWidth: 'max-w-[145px]',
    messageAlign: 'text-right items-end',
    messageTone: 'ivory',
    messageWashClass: 'inset-x-0 bottom-0 h-[28%]',
    messageWashStyle: {
      background: 'linear-gradient(0deg, rgba(2,44,34,.55), rgba(2,44,34,.2), rgba(2,44,34,0))',
    },
    downloadText: { x: 0.9, y: 0.78, maxWidth: 0.38, align: 'right', wash: 'bottomGreen' },
  },
  {
    id: 'template-photo-4',
    name: 'Ivory Mountain',
    mood: 'Clean monochrome',
    image: '/assets/templates/template-photo-4.jpg',
    aspectRatio: '2 / 3',
    previewWidth: 'min(82vw, 370px)',
    objectPosition: 'center',
    messagePosition: 'bottom-10 left-8',
    messageWidth: 'max-w-[230px]',
    messageAlign: 'text-left items-start',
    messageTone: 'mono',
    messageWashClass: 'inset-x-0 bottom-0 h-[30%]',
    messageWashStyle: {
      background: 'linear-gradient(0deg, rgba(0,0,0,.4), rgba(0,0,0,.1), rgba(0,0,0,0))',
    },
    downloadText: { x: 0.12, y: 0.78, maxWidth: 0.55, align: 'left', wash: 'bottomBlackSoft' },
  },
  {
    id: 'template-photo-5',
    name: 'Lantern Square',
    mood: 'Decorative mosque',
    image: '/assets/templates/template-photo-5.jpg',
    aspectRatio: '1 / 1',
    previewWidth: 'min(86vw, 500px)',
    objectPosition: 'center',
    messagePosition: 'top-8 left-8',
    messageWidth: 'max-w-[210px]',
    messageAlign: 'text-left items-start',
    messageTone: 'gold',
    messageWashClass: 'inset-y-0 left-0 w-[42%]',
    messageWashStyle: {
      background: 'linear-gradient(90deg, rgba(2,44,34,.4), rgba(2,44,34,.1), rgba(2,44,34,0))',
    },
    downloadText: { x: 0.08, y: 0.13, maxWidth: 0.38, align: 'left', wash: 'leftGreen' },
  },
  {
    id: 'template-photo-6',
    name: 'Arch Poster',
    mood: 'Cinematic dark',
    image: '/assets/templates/template-photo-6.jpg',
    aspectRatio: '1 / 1',
    previewWidth: 'min(86vw, 500px)',
    objectPosition: 'center',
    messagePosition: 'top-[18%] left-10',
    messageWidth: 'max-w-[220px]',
    messageAlign: 'text-left items-start',
    messageTone: 'gold',
    messageWashClass: 'inset-y-0 left-0 w-[44%]',
    messageWashStyle: {
      background: 'linear-gradient(90deg, rgba(0,0,0,.6), rgba(0,0,0,.2), rgba(0,0,0,0))',
    },
    downloadText: { x: 0.08, y: 0.17, maxWidth: 0.4, align: 'left', wash: 'leftBlack' },
  },
];

export const getTemplateById = (id) =>
  EID_TEMPLATES.find((template) => template.id === id) || EID_TEMPLATES[0];
