const PORTRAIT_CARD_SIZE = {
  aspectRatio: '472 / 626',
  paddingBottomPercent: '132.6%',
};

export const EID_TEMPLATES = [
  {
    id: 'template-photo-1',
    name: 'خروف دافئ',
    mood: 'ستايل صورة دافئة',
    image: '/assets/templates/template-photo-1.jpg',
    ...PORTRAIT_CARD_SIZE,
    objectPosition: 'center',
    messagePosition: 'bottom-8 right-7',
    messageWidth: 'max-w-[210px]',
    messageAlign: 'text-right items-end',
    messageTone: 'gold',
    messageWashClass: 'inset-x-0 bottom-0 h-[32%]',
    messageWashStyle: {
      background: 'linear-gradient(0deg, rgba(0,0,0,.5), rgba(0,0,0,.2), rgba(0,0,0,0))',
    },
    downloadText: { x: 0.84, y: 0.73, maxWidth: 0.42, align: 'right', wash: 'bottomBlack' },
  },
  {
    id: 'template-photo-2',
    name: 'كبش ومسجد',
    mood: 'ستايل إسلامي فاخر',
    image: '/assets/templates/template-photo-2.jpg',
    ...PORTRAIT_CARD_SIZE,
    objectPosition: 'center',
    messagePosition: 'bottom-[15%] left-8',
    messageWidth: 'max-w-[190px]',
    messageAlign: 'text-left items-start',
    messageTone: 'gold',
    messageWashClass: 'inset-y-0 left-0 w-[45%]',
    messageWashStyle: {
      background: 'linear-gradient(90deg, rgba(0,0,0,.55), rgba(0,0,0,.2), rgba(0,0,0,0))',
    },
    downloadText: { x: 0.08, y: 0.68, maxWidth: 0.38, align: 'left', wash: 'leftBlack' },
  },
  {
    id: 'template-photo-3',
    name: 'أخضر أنيق',
    mood: 'بطاقة طويلة',
    image: '/assets/templates/template-photo-3.jpg',
    aspectRatio: '9 / 16',
    paddingBottomPercent: '177.8%',
    objectPosition: 'center',
    messagePosition: 'bottom-8 right-6',
    messageWidth: 'max-w-[145px]',
    messageAlign: 'text-right items-end',
    messageTone: 'ivory',
    messageWashClass: 'inset-x-0 bottom-0 h-[28%]',
    messageWashStyle: {
      background: 'linear-gradient(0deg, rgba(2,44,34,.55), rgba(2,44,34,.2), rgba(2,44,34,0))',
    },
    downloadText: { x: 0.9, y: 0.78, maxWidth: 0.38, align: 'right', wash: 'bottomGreen' },
  },
  {
    id: 'template-photo-4',
    name: 'جبل أبيض',
    mood: 'ستايل هادئ ونظيف',
    image: '/assets/templates/template-photo-4.jpg',
    aspectRatio: '2 / 3',
    paddingBottomPercent: '150%',
    objectPosition: 'center',
    messagePosition: 'bottom-10 left-8',
    messageWidth: 'max-w-[230px]',
    messageAlign: 'text-left items-start',
    messageTone: 'mono',
    messageWashClass: 'inset-x-0 bottom-0 h-[30%]',
    messageWashStyle: {
      background: 'linear-gradient(0deg, rgba(0,0,0,.4), rgba(0,0,0,.1), rgba(0,0,0,0))',
    },
    downloadText: { x: 0.12, y: 0.78, maxWidth: 0.55, align: 'left', wash: 'bottomBlackSoft' },
  },
  {
    id: 'template-photo-5',
    name: 'فوانيس العيد',
    mood: 'مسجد وفوانيس',
    image: '/assets/templates/template-photo-5.jpg',
    aspectRatio: '1 / 1',
    paddingBottomPercent: '100%',
    objectPosition: 'center',
    messagePosition: 'top-8 left-8',
    messageWidth: 'max-w-[210px]',
    messageAlign: 'text-left items-start',
    messageTone: 'gold',
    messageWashClass: 'inset-y-0 left-0 w-[42%]',
    messageWashStyle: {
      background: 'linear-gradient(90deg, rgba(2,44,34,.4), rgba(2,44,34,.1), rgba(2,44,34,0))',
    },
    downloadText: { x: 0.08, y: 0.13, maxWidth: 0.38, align: 'left', wash: 'leftGreen' },
  },
  {
    id: 'template-photo-6',
    name: 'بوستر القوس',
    mood: 'ستايل سينمائي',
    image: '/assets/templates/template-photo-6.jpg',
    aspectRatio: '1 / 1',
    paddingBottomPercent: '100%',
    objectPosition: 'center',
    messagePosition: 'top-[18%] left-10',
    messageWidth: 'max-w-[220px]',
    messageAlign: 'text-left items-start',
    messageTone: 'gold',
    messageWashClass: 'inset-y-0 left-0 w-[44%]',
    messageWashStyle: {
      background: 'linear-gradient(90deg, rgba(0,0,0,.6), rgba(0,0,0,.2), rgba(0,0,0,0))',
    },
    downloadText: { x: 0.08, y: 0.17, maxWidth: 0.4, align: 'left', wash: 'leftBlack' },
  },
];

export const getTemplateById = (id) =>
  EID_TEMPLATES.find((template) => template.id === id) || EID_TEMPLATES[0];
