export const EID_TEMPLATES = [
  {
    id: 'template-photo-1',
    name: 'Classic Sheep',
    mood: 'Warm straw photo',
    image: '/assets/templates/template-photo-1.jpg',
    aspectRatio: '4 / 5',
    previewWidth: 'min(86vw, 400px)',
    objectPosition: 'center',
    tagPosition: 'bottom-7 right-6 text-right',
    tagTone: 'dark',
    tagWidth: 'max-w-[190px]',
  },
  {
    id: 'template-photo-2',
    name: 'Dark Ram',
    mood: 'Minimal premium',
    image: '/assets/templates/template-photo-2.jpg',
    aspectRatio: '4 / 5',
    previewWidth: 'min(86vw, 400px)',
    objectPosition: 'center',
    tagPosition: 'bottom-8 left-1/2 -translate-x-1/2 text-center',
    tagTone: 'dark',
    tagWidth: 'max-w-[230px]',
  },
  {
    id: 'template-photo-3',
    name: 'Kasturii Green',
    mood: 'Tall story card',
    image: '/assets/templates/template-photo-3.jpg',
    aspectRatio: '9 / 16',
    previewWidth: 'min(78vw, 335px)',
    objectPosition: 'center',
    tagPosition: 'top-[38%] left-1/2 -translate-x-1/2 text-center',
    tagTone: 'green',
    tagWidth: 'max-w-[250px]',
  },
  {
    id: 'template-photo-4',
    name: 'Ivory Mountain',
    mood: 'Clean monochrome',
    image: '/assets/templates/template-photo-4.jpg',
    aspectRatio: '2 / 3',
    previewWidth: 'min(82vw, 370px)',
    objectPosition: 'center',
    tagPosition: 'top-[24%] left-8 text-left',
    tagTone: 'light',
    tagWidth: 'max-w-[240px]',
  },
  {
    id: 'template-photo-5',
    name: 'Lantern Square',
    mood: 'Decorative mosque',
    image: '/assets/templates/template-photo-5.jpg',
    aspectRatio: '1 / 1',
    previewWidth: 'min(86vw, 500px)',
    objectPosition: 'center',
    tagPosition: 'top-6 left-1/2 -translate-x-1/2 text-center',
    tagTone: 'green',
    tagWidth: 'max-w-[270px]',
  },
  {
    id: 'template-photo-6',
    name: 'Arch Poster',
    mood: 'Cinematic dark',
    image: '/assets/templates/template-photo-6.jpg',
    aspectRatio: '1 / 1',
    previewWidth: 'min(86vw, 500px)',
    objectPosition: 'center',
    tagPosition: 'bottom-7 left-1/2 -translate-x-1/2 text-center',
    tagTone: 'dark',
    tagWidth: 'max-w-[250px]',
  },
];

export const getTemplateById = (id) =>
  EID_TEMPLATES.find((template) => template.id === id) || EID_TEMPLATES[0];
